import {
	FolderOpen,
	Save,
	Sun,
	Moon,
	Settings,
	Search,
	Library,
	List,
	BookOpen,
	Clapperboard,
	Volume2,
	Play,
	Pause,
	SkipBack,
	SkipForward,
	Eye,
	EyeOff as EyeOffAlt,
	RefreshCw,
	X,
	CheckCircle,
	Type,
	FileText,
	ChevronDown,
	ChevronUp,
	Download,
	Upload,
	RotateCcw,
	AlertCircle,
	Sparkles,
	User,
	VolumeX,
	Database,
	PenLine,
	HardDrive,
	Clock,
	File as FileIcon,
	Plus,
} from "lucide-react";

export const Icons = {
	import: FolderOpen,
	save: Save,
	saveOriginal: Database,
	cache: HardDrive,
	sun: Sun,
	moon: Moon,
	settings: Settings,
	search: Search,
	library: Library,
	list: List,
	book: BookOpen,
	script: Clapperboard,
	volume: Volume2,
	volumeMute: VolumeX,
	play: Play,
	pause: Pause,
	skipBack: SkipBack,
	skipForward: SkipForward,
	eye: Eye,
	eyeOff: EyeOffAlt,
	refresh: RefreshCw,
	close: X,
	check: CheckCircle,
	typo: Type,
	grammar: PenLine,
	punctuation: FileText,
	chevronDown: ChevronDown,
	chevronUp: ChevronUp,
	download: Download,
	upload: Upload,
	reset: RotateCcw,
	error: AlertCircle,
	sparkle: Sparkles,
	user: User,
	calendar: Clock,
	file: FileIcon,
	plus: Plus,
};

export type IconName = keyof typeof Icons;
