import {
	FolderOpen,
	Save,
	Sun,
	Moon,
	Settings,
	Search,
	Library,
	List,
	BookOpen,
	Clapperboard,
	Volume2,
	Play,
	Pause,
	SkipBack,
	SkipForward,
	Eye,
	EyeOff as EyeOffAlt,
	RefreshCw,
	X,
	CheckCircle,
	CircleCheckBig,
	Type,
	FileText,
	ChevronDown,
	ChevronUp,
	Download,
	Upload,
	RotateCcw,
	AlertCircle,
	Sparkles,
	User,
	VolumeX,
	Database,
	PenLine,
	HardDrive,
	Clock,
	File as FileIcon,
	Plus,
	Minus,
	Bolt,
	BookAudio,
	LineStyle,
	BookHeadphones,
	CheckSquare,
	FileOutput,
	DownloadCloud,
	BarChart3,
	ListTodo,
	Trash2,
	Loader2,
	Circle,
	AlertTriangle,
	Edit,
	Save as SaveIcon,
	Copy,
	UserRound,
	UserRoundPlus,
	UserRoundPen,
	ListOrdered,
} from "lucide-react";

export const Icons = {
	import: FolderOpen,
	save: Save,
	saveOriginal: Database,
	cache: HardDrive,
	sun: Sun,
	moon: Moon,
	settings: Settings,
	search: Search,
	library: Library,
	list: List,
	book: BookOpen,
	script: Clapperboard,
	volume: Volume2,
	volumeMute: VolumeX,
	play: Play,
	pause: Pause,
	skipBack: SkipBack,
	skipForward: SkipForward,
	eye: Eye,
	eyeOff: EyeOffAlt,
	refresh: RefreshCw,
	close: X,
	x: X,
	check: CheckCircle,
	checkCircle: CheckCircle,
	circleCheckBig: CircleCheckBig,
	typo: Type,
	grammar: PenLine,
	punctuation: FileText,
	chevronDown: ChevronDown,
	chevronUp: ChevronUp,
	download: Download,
	downloadCloud: DownloadCloud,
	upload: Upload,
	reset: RotateCcw,
	error: AlertCircle,
	alertCircle: AlertCircle,
	alertTriangle: AlertTriangle,
	sparkle: Sparkles,
	user: User,
	calendar: Clock,
	clock: Clock,
	file: FileIcon,
	plus: Plus,
	minus: Minus,
	bolt: Bolt,
	bookAudio: BookAudio,
	lineStyle: LineStyle,
	bookHeadphones: BookHeadphones,
	checkAll: CheckSquare,
	fileOutput: FileOutput,
	barChart3: BarChart3,
	listTodo: ListTodo,
	listOrdered: ListOrdered,
	trash2: Trash2,
	loader2: Loader2,
	circle: Circle,
	edit: Edit,
	saveIcon: SaveIcon,
	copy: Copy,
	userRound: UserRound,
	userRoundPlus: UserRoundPlus,
	userRoundPen: UserRoundPen,
};

export type IconName = keyof typeof Icons;
